name: Python Runner

on:
  schedule:
    - cron: '0 23 * * 1'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install jupyter
        pip install pandas
        pip install TableauScraper
    - name: Run notebook
      run: |
        jupyter nbconvert --to notebook --execute sf_crime_scraper.ipynb
    - name: Commit results
      run: |
        git add -A
        git commit -m 'New SF crime data collected' || echo "No changes"
        git push origin || echo "No changes to commit"
