name: Python Scraper

# Runs the scraper late Monday evening, after SFPD usually updates;
# if for some reason they update late, need to run workflow manually
on:
  schedule:
    - cron: '0 23 * * 1'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install notebook jupyter pandas TableauScraper datetime
    - name: Run scraper
      run: jupyter execute sf_crime_scraper.ipynb
    - name: Commit results
      run: |
        git add -A
        git commit -m 'New SF crime data collected' || echo "No changes"
        git status  # Add this line for debugging
        git push origin || echo "No changes to commit"
